version: "2"
services:
  node-red:
    container_name: nodered_container
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./volumes/node-red:/data
    networks:
      solar_network:
        ipv4_address: 172.20.0.4

  mysql:
    container_name: mysql_container
    image: mysql:latest
    ports:
      - "3360:3306"
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      solar_network:
        ipv4_address: 172.20.0.5

networks:
  solar_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
