version: "2"
services:
    node-red:
        container_name: nodered_container
        image: nodered/node-red:latest
        ports:
            - "1880:1880"
        volumes:
            - ./volumes/node-red:/data
        networks:
            solar_network:
                ipv4_address: 172.20.0.4

    influxdb:
        image: quay.io/influxdb/influxdb:v2.0.3
        container_name: influxdb_container
        environment:
          - INFLUXDB_DB=telegraf
          - INFLUXDB_USER=telegraf
          - INFLUXDB_ADMIN_ENABLED=true
          - INFLUXDB_ADMIN_USER=rpaha
          - INFLUXDB_ADMIN_PASSWORD=rpaha
        ports:
          - "8086:8086"
          - "8082:8082"
          - "8089:8089/udp"
        volumes:
            - ./volumes/influxdb:/var/lib/influxdb
        networks:
            solar_network:
                ipv4_address: 172.20.0.5

networks:
  solar_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
