CREATE USER IF NOT EXISTS'rpaha'@'%' IDENTIFIED BY 'rpaha';
GRANT ALL PRIVILEGES ON *.* TO 'rpaha'@'%';
FLUSH PRIVILEGES;

CREATE SCHEMA IF NOT EXISTS `collector`;

CREATE TABLE IF NOT EXISTS `collector`.`ecg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hr_in` INT NOT NULL,
  PRIMARY KEY (`id`));

use collector;
